/*
 * Copyright (C) 2014 - 2015 Healthcare Services Platform Consortium
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.hspconsortium.platform.messaging

dialect "mvel"

import org.hspconsortium.platform.messaging.model.Container
import org.hspconsortium.platform.messaging.model.ObservationContainer

rule "Bilirubin Observation"
    when
        $c: ObservationContainer(
              // is bilirubin
              getObservation().getCode() != null
              && getObservation().getCode().getCodingFirstRep() != null
              && getObservation().getCode().getCodingFirstRep().getCode() == "58941-6"
            )
    then
        $c.setProcessingMessage("Hello World!");
        $c.setRouteChannel("123");
end
